name: Execute tests

on:
  workflow_dispatch:
    inputs:
      script:
        description: 'Script'
        required: true
        default: 'banking'
        type: choice
        options:
          - all
          - banking
          - cucumber

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t banking-test .

      - name: Run Cypress Tests
        env:
          SCRIPT: ${{ inputs.script }}
        run: docker run -e SCRIPT=$SCRIPT banking-test

      - name: Create and upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: My Artifacts
          path: ./cypress/videos
