name: Execute tests

on:
  workflow_dispatch:
    inputs:
      script:
        description: 'script'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - banking
          - cucumber

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker run -e SCRIPT=${{ github.event.inputs.script }} banking-test

      - name: Run Cypress Tests
        run: docker run execute-test
      
      - name: Create and upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: My Artifacts
          path: ./cypress/videos